#page title
page_title                                : #YouWidget - Widget for YouTube            # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1587136720                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : EXIFixer - Photo EXIF Metadata                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Intelligently fix your iPhone Photos Metadata.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : James Shaw
your_link                                 : https://www.shaw-james.com
your_city                                 : York, England
email_address                             :
facebook_username                         :
instagram_username                        : jsh8w
twitter_username                          : jsh8w
github_username                           : jsh8w
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : View iPhone Photo Metadata
    description                           : View EXIF Metadata for all your iPhone photos.
    fontawesome_icon_name                 : mobile

  - title                                 : Fix and Edit All Metadata
    description                           : View fixtures and results for your favourite teams.
    fontawesome_icon_name                 : hammer

  - title                                 : 50+ Metadata Tags
    description                           : Over 50 Metadata Tags to view and edit.
    fontawesome_icon_name                 : tags

  - title                                 : Intelligent Location Suggestions
    description                           : EXIFixer intelligently suggests locations for photos with missing GPS data.
    fontawesome_icon_name                 : brain

  - title                                 : Map Locations
    description                           : View GPS locations on a beautiful designed map.
    fontawesome_icon_name                 : map

  - title                                 : Beautiful App Design
    description                           : The clean, simple design makes the app intuitive to use.
    fontawesome_icon_name                 : palette



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#0b0f27"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#0b0f27"
feature_icons_background_color            : "#bfbfbf"

social_icons_foreground_color             : "#0b0f27"
social_icons_background_color             : "#bfbfbf"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
